module.exports = [
 {id:1,title:'Pochampally Ikat Saree',cat:'Textiles',craft:'Ikat handloom weaving',material:'Cotton',color:null,dims:null,price:4200,qty:4,art:'radha',status:'published',photos:['ikat-saree'],ai:true,desc:'Handwoven ikat saree from Bhoodan Pochampally. Pattern details and dimensions to be confirmed by the artisan.',kw:['ikat saree','pochampally','handloom'],views:236},
 {id:2,title:'Handwoven Cotton Stole',cat:'Textiles',craft:'Handloom weaving',material:'Cotton',color:'Indigo',dims:null,price:1250,qty:18,art:'radha',status:'published',photos:[],ai:true,desc:'Handwoven cotton stole dyed with natural indigo, with a traditional woven border.',kw:['cotton stole','indigo','handloom'],views:420},
 {id:3,title:'Ikat Cotton Stole, Madder Red',cat:'Textiles',craft:'Ikat handloom weaving',material:'Cotton',color:'Madder red',dims:null,price:1180,qty:12,art:'radha',status:'published',photos:[],ai:false,desc:'Cotton stole in ikat weave, dyed in madder red.',kw:['ikat stole','madder'],views:310},
 {id:4,title:'Block Print Table Runner',cat:'Textiles',craft:'Block printing',material:'Cotton',color:null,dims:null,price:960,qty:20,art:'radha',status:'published',photos:[],ai:false,desc:'Cotton table runner with a hand block-printed border.',kw:['table runner','block print'],views:176},
 {id:5,title:'Festive Ikat Stole',cat:'Textiles',craft:'Ikat handloom weaving',material:null,color:null,dims:null,price:1980,qty:6,art:'radha',status:'draft',photos:[],ai:true,desc:'',kw:[],views:0},
 {id:6,title:'Terracotta Water Pot',cat:'Home Decor',craft:'Wheel-thrown pottery',material:'Terracotta',color:'Terracotta',dims:null,price:680,qty:40,art:'meera',status:'published',photos:['terracotta-pots'],ai:false,desc:'Wheel-thrown clay pot for storing water, fired in a wood kiln.',kw:['terracotta','water pot'],views:0},
 {id:7,title:'Bamboo Storage Basket',cat:'Home Decor',craft:'Cane weaving',material:'Bamboo',color:'Natural',dims:null,price:540,qty:60,art:'jolly',status:'published',photos:['bamboo-weaver'],ai:false,desc:'Woven bamboo basket with an arched handle.',kw:['bamboo','basket'],views:0},
 {id:8,title:'Dhokra Brass Lamp',cat:'Metalcraft',craft:'Dhokra casting',material:'Brass',color:null,dims:null,price:1890,qty:8,art:'sukru',status:'review',photos:[],ai:true,flag:'Material unconfirmed by artisan',desc:'Brass lamp cast by the lost-wax method.',kw:['dhokra','brass lamp'],views:0},
 {id:9,title:'Madhubani Fish Painting',cat:'Art',craft:'Madhubani painting',material:'Handmade paper',color:null,dims:null,price:1500,qty:10,art:'sunita',status:'published',photos:[],ai:false,desc:'Hand-painted fish motif in the Madhubani style.',kw:['madhubani','fish'],views:0},
 {id:10,title:'Channapatna Toy Set',cat:'Toys',craft:'Lacquerware',material:'Wood',color:'Assorted',dims:null,price:890,qty:30,art:'imran',status:'published',photos:[],ai:false,desc:'Stackable wooden toys turned on a lathe and lacquered.',kw:['channapatna','wooden toys'],views:0},
 {id:11,title:'Hand-Painted Story Bottles',cat:'Art',craft:'Bottle art painting',material:'Glass',color:'Multicolour',dims:null,price:1450,qty:9,art:'sunita',status:'published',photos:['painted-bottles'],ai:false,desc:'Recycled glass bottles hand-painted with mythological folk-art scenes, sold as a pair.',kw:['painted bottles','folk art','glass'],views:0},
 {id:12,title:'Mirror-Work Wall Hanging',cat:'Home Decor',craft:'Mirror embroidery (Lippan)',material:'Felt and mirror',color:'Multicolour',dims:null,price:520,qty:25,art:'meera',status:'published',photos:['mirror-tassel'],ai:false,desc:'Layered mirror-work wall hanging with hand-stitched felt discs and tassels, in the Kutch mirror-embroidery style.',kw:['mirror work','wall hanging','kutch'],views:0},
 {id:13,title:'Hand-Painted Clay Diyas (Set of 6)',cat:'Home Decor',craft:'Hand-painted terracotta',material:'Terracotta',color:'Multicolour',dims:null,price:390,qty:50,art:'meera',status:'published',photos:['diya-painting'],ai:false,desc:'Set of six terracotta diyas, hand-painted with festive motifs.',kw:['diya','terracotta','festive'],views:0},
 {id:14,title:'Carved Wooden Horse Showpiece',cat:'Home Decor',craft:'Wood carving',material:'Wood',color:'Brown and gold',dims:null,price:1250,qty:14,art:'imran',status:'published',photos:['wooden-horse'],ai:false,desc:'Hand-carved wooden horse showpiece with brass detailing.',kw:['wooden horse','showpiece','carving'],views:0},
 {id:15,title:'Jaipur Blue Pottery Vase',cat:'Home Decor',craft:'Blue pottery',material:'Ceramic',color:'Blue and white',dims:null,price:1650,qty:11,art:'kavita',status:'published',photos:['blue-pottery-vase'],ai:false,desc:'Hand-thrown and hand-painted Jaipur blue pottery vase, glazed in the traditional style.',kw:['blue pottery','jaipur','vase'],views:0},
 {id:16,title:'Hand-Painted Wooden Elephant',cat:'Home Decor',craft:'Wood carving and painting',material:'Wood',color:'Blue and multicolour',dims:null,price:990,qty:16,art:'imran',status:'published',photos:['painted-elephant'],ai:false,desc:'Carved wooden elephant showpiece, hand-painted with intricate detailing.',kw:['wooden elephant','showpiece','hand-painted'],views:0}
];
